/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package num;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import model.MonteCarlo;
import model.Solver;

/**
 *
 * @author Ondrej
 */
public class Menu extends javax.swing.JFrame{

  public static boolean first = true;
  public static boolean second = true;
  public static boolean third = true;
  boolean runFlag = false;

  /**
   * Creates new form Menu
   */
  public Menu(){
    initComponents();
    this.jLabel7.setText("");
    this.jLabel9.setText("");
    this.jLabel11.setText("");
    this.jLabel13.setText("");
    this.jLabel19.setText("");
    this.jLabel20.setText("");
    this.jTextArea1.setText("");
    this.jTextArea2.setText("");
    this.setTitle("Numerické metody");
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroup1 = new javax.swing.ButtonGroup();
    jPanel1 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jRadioButton1 = new javax.swing.JRadioButton();
    jRadioButton2 = new javax.swing.JRadioButton();
    jRadioButton3 = new javax.swing.JRadioButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();
    jScrollPane2 = new javax.swing.JScrollPane();
    jTextArea2 = new javax.swing.JTextArea();
    jButton1 = new javax.swing.JButton();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();
    jLabel11 = new javax.swing.JLabel();
    jLabel12 = new javax.swing.JLabel();
    jLabel13 = new javax.swing.JLabel();
    jLabel14 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel15 = new javax.swing.JLabel();
    jScrollPane3 = new javax.swing.JScrollPane();
    jTextArea3 = new javax.swing.JTextArea();
    jTextField1 = new javax.swing.JTextField();
    jLabel16 = new javax.swing.JLabel();
    jButton2 = new javax.swing.JButton();
    jLabel17 = new javax.swing.JLabel();
    jLabel18 = new javax.swing.JLabel();
    jLabel19 = new javax.swing.JLabel();
    jLabel20 = new javax.swing.JLabel();
    jLabel21 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(204, 204, 255));

    jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
    jLabel2.setText("3^x = 200 - x^3");

    buttonGroup1.add(jRadioButton1);
    jRadioButton1.setSelected(true);
    jRadioButton1.setText("1E-2");
    jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jRadioButton1ActionPerformed(evt);
      }
    });

    buttonGroup1.add(jRadioButton2);
    jRadioButton2.setText("1E-4");

    buttonGroup1.add(jRadioButton3);
    jRadioButton3.setText("1E-3");
    jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jRadioButton3ActionPerformed(evt);
      }
    });

    jTextArea1.setColumns(20);
    jTextArea1.setRows(5);
    jScrollPane1.setViewportView(jTextArea1);

    jTextArea2.setColumns(20);
    jTextArea2.setRows(5);
    jScrollPane2.setViewportView(jTextArea2);

    jButton1.setText("Řešit");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel3.setText("Požadovaná přesnost");

    jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel4.setText("Půlení intervalů");

    jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel5.setText("Metoda sečen");

    jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel6.setText("iterace");

    jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel7.setText("Výsledek");

    jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel8.setText("Výsledek");

    jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel9.setText("iterace");
    jLabel9.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
      public void propertyChange(java.beans.PropertyChangeEvent evt) {
        jLabel9PropertyChange(evt);
      }
    });

    jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel10.setText("iterace");

    jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel11.setText("Výsledek");

    jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel12.setText("Výsledek");

    jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel13.setText("iterace");
    jLabel13.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
      public void propertyChange(java.beans.PropertyChangeEvent evt) {
        jLabel13PropertyChange(evt);
      }
    });

    jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
    jLabel14.setText("Řešení rovnice");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5)
            .addGap(528, 528, 528))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel14)
            .addGap(18, 18, 18)
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3)
            .addGap(18, 18, 18)
            .addComponent(jRadioButton1)
            .addGap(18, 18, 18)
            .addComponent(jRadioButton3)
            .addGap(18, 18, 18)
            .addComponent(jRadioButton2)
            .addGap(18, 18, 18)
            .addComponent(jButton1)
            .addGap(27, 27, 27))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(70, 70, 70)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(70, 70, 70)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addGap(322, 322, 322))))))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(jRadioButton1)
          .addComponent(jRadioButton2)
          .addComponent(jRadioButton3)
          .addComponent(jButton1)
          .addComponent(jLabel3)
          .addComponent(jLabel14))
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(jLabel5))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
          .addComponent(jScrollPane2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel6)
          .addComponent(jLabel7)
          .addComponent(jLabel8)
          .addComponent(jLabel9)
          .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(jLabel10)
            .addComponent(jLabel11)
            .addComponent(jLabel12)
            .addComponent(jLabel13)))
        .addGap(19, 19, 19))
    );

    jPanel2.setBackground(new java.awt.Color(204, 204, 255));

    jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
    jLabel1.setText("Výpočet plochy pomocí metody Monte Carlo");

    jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
    jLabel15.setText("pro f(x) = sin(x)   x...<0;PI>");

    jTextArea3.setColumns(20);
    jTextArea3.setRows(5);
    jScrollPane3.setViewportView(jTextArea3);

    jTextField1.setText("0.01");

    jLabel16.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
    jLabel16.setText("POŽADOVANÁ PŘESNOST");

    jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jButton2.setText("VYPOČTI OBSAH");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });

    jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel17.setText("iterace");

    jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel18.setText("Výsledek");

    jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel19.setText("Výsledek");

    jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel20.setText("iterace");
    jLabel20.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
      public void propertyChange(java.beans.PropertyChangeEvent evt) {
        jLabel20PropertyChange(evt);
      }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel1)
              .addComponent(jLabel15))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jLabel16)
                    .addGap(18, 18, 18)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addGap(70, 70, 70)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addGap(161, 161, 161))))))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel15)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel16)
              .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(35, 35, 35)
            .addComponent(jButton2)
            .addGap(23, 23, 23)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel17)
              .addComponent(jLabel19)
              .addComponent(jLabel18)
              .addComponent(jLabel20))))
        .addContainerGap(28, Short.MAX_VALUE))
    );

    jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel21.setText("Ondřej Schrek 2015");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jLabel21)
        .addGap(569, 569, 569))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGap(18, 18, 18)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel21)
        .addGap(5, 5, 5))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    double prec = 0;
    if(this.jRadioButton1.isSelected()){
      prec = 0.001;
    }
    if(this.jRadioButton2.isSelected()){
      prec = 0.0001;
    }
    if(this.jRadioButton3.isSelected()){
      prec = 0.00001;
    }
    if(first == true && second == true){
      Menu.first = false;
      Menu.second = false;
      runFlag = false;
      this.jLabel7.setText("");
      this.jLabel9.setText("");
      this.jLabel11.setText("");
      this.jLabel13.setText("");
      this.jTextArea1.setText("");
      this.jTextArea2.setText("");
      this.jTextArea1.setBackground(Color.white);
      this.jLabel7.setForeground(Color.black);
      this.jLabel9.setForeground(Color.black);
      this.jTextArea2.setBackground(Color.white);
      this.jLabel11.setForeground(Color.black);
      this.jLabel13.setForeground(Color.black);
      Solver solv = new Solver(prec);
      BisecThread t1 = new BisecThread("vlaknoBisec", solv, this.jTextArea1, this.jLabel7, this.jLabel9);
      SectThread t2 = new SectThread("vlaknoBisec", solv, this.jTextArea2, this.jLabel11, this.jLabel13);
      runFlag = true;
    }
    //Thread.sleep(2000);
  }//GEN-LAST:event_jButton1ActionPerformed

  private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jRadioButton1ActionPerformed

  private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jRadioButton3ActionPerformed

  private void jLabel9PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel9PropertyChange
    if(first && second && runFlag){
      if(Integer.parseInt(this.jLabel9.getText()) < Integer.parseInt(this.jLabel13.getToolTipText())){
        this.jTextArea1.setBackground(Color.green);
        this.jLabel7.setForeground(Color.green);
        this.jLabel9.setForeground(Color.green);
        this.jTextArea2.setBackground(Color.red);
        this.jLabel11.setForeground(Color.red);
        this.jLabel13.setForeground(Color.red);
      }else{
        this.jTextArea1.setBackground(Color.red);
        this.jLabel7.setForeground(Color.red);
        this.jLabel9.setForeground(Color.red);
        this.jTextArea2.setBackground(Color.green);
        this.jLabel11.setForeground(Color.green);
        this.jLabel13.setForeground(Color.green);
      }
    }
  }//GEN-LAST:event_jLabel9PropertyChange

  private void jLabel13PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel13PropertyChange
    if(first && second && runFlag){
      if(Integer.parseInt(this.jLabel9.getText()) < Integer.parseInt(this.jLabel13.getToolTipText())){
        this.jTextArea1.setBackground(Color.green);
        this.jLabel7.setForeground(Color.green);
        this.jLabel9.setForeground(Color.green);
        this.jTextArea2.setBackground(Color.red);
        this.jLabel11.setForeground(Color.red);
        this.jLabel13.setForeground(Color.red);
      }else{
        this.jTextArea1.setBackground(Color.red);
        this.jLabel7.setForeground(Color.red);
        this.jLabel9.setForeground(Color.red);
        this.jTextArea2.setBackground(Color.green);
        this.jLabel11.setForeground(Color.green);
        this.jLabel13.setForeground(Color.green);
      }
    }
  }//GEN-LAST:event_jLabel13PropertyChange

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    if(third){
      third=false;
      this.jTextArea3.setText("");
      MonteCarlo mc = new MonteCarlo(Double.parseDouble(jTextField1.getText()));
      MonteThread t1 = new MonteThread("vlaknoBisec", mc, this.jTextArea3, this.jLabel19, this.jLabel20);
    }
  }//GEN-LAST:event_jButton2ActionPerformed

  private void jLabel20PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel20PropertyChange
    // TODO add your handling code here:
  }//GEN-LAST:event_jLabel20PropertyChange

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]){
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try{
      for(javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()){
        if("Nimbus".equals(info.getName())){
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }catch(ClassNotFoundException ex){
      java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }catch(InstantiationException ex){
      java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }catch(IllegalAccessException ex){
      java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }catch(javax.swing.UnsupportedLookAndFeelException ex){
      java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable(){
      public void run(){
        new Menu().setVisible(true);
      }
    });
  }

  class MonteThread implements Runnable{

    String name;
    Thread t;
    MonteCarlo mont;
    JTextArea txtBox;
    JLabel vysledek;
    JLabel iterace;

    public MonteThread(String name, MonteCarlo mont, JTextArea txtBox, JLabel vysledek, JLabel iterace){
      this.name = name;
      t = new Thread(this, name);
      t.start();
      this.mont = mont;
      this.txtBox = txtBox;
      this.vysledek = vysledek;
      this.iterace = iterace;
    }

    public void run(){
      try{
        mont.doMonteCarlo(this.txtBox, this.vysledek, this.iterace);
      }catch(Exception ex){
        Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
      }
    }
  }

  class BisecThread implements Runnable{

    String name;
    Thread t;
    Solver solv;
    JTextArea txtBox;
    JLabel vysledek;
    JLabel iterace;

    public BisecThread(String name, Solver solv, JTextArea txtBox, JLabel vysledek, JLabel iterace){
      this.name = name;
      t = new Thread(this, name);
      t.start();
      this.solv = solv;
      this.txtBox = txtBox;
      this.vysledek = vysledek;
      this.iterace = iterace;
    }

    public void run(){
      try{
        solv.doBisection(0.0, 5.0, this.txtBox, this.vysledek, this.iterace);
      }catch(Exception ex){
        Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
      }
    }
  }

  class SectThread implements Runnable{

    String name;
    Thread t;
    Solver solv;
    JTextArea txtBox;
    JLabel vysledek;
    JLabel iterace;

    public SectThread(String name, Solver solv, JTextArea txtBox, JLabel vysledek, JLabel iterace){
      this.name = name;
      t = new Thread(this, name);
      t.start();
      this.solv = solv;
      this.txtBox = txtBox;
      this.vysledek = vysledek;
      this.iterace = iterace;
    }

    public void run(){
      try{
        solv.doSectant(0.0, 5.0, this.txtBox, this.vysledek, this.iterace);
      }catch(Exception ex){
        Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
      }
    }
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel14;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel16;
  private javax.swing.JLabel jLabel17;
  private javax.swing.JLabel jLabel18;
  private javax.swing.JLabel jLabel19;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel20;
  private javax.swing.JLabel jLabel21;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JRadioButton jRadioButton1;
  private javax.swing.JRadioButton jRadioButton2;
  private javax.swing.JRadioButton jRadioButton3;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JTextArea jTextArea1;
  private javax.swing.JTextArea jTextArea2;
  private javax.swing.JTextArea jTextArea3;
  private javax.swing.JTextField jTextField1;
  // End of variables declaration//GEN-END:variables
}
